(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/gen_GNP_values.clp"))
(load ?*path*)
(load-facts "USR-CLIPS-facts.dat")
(load-facts "mrs_feature_info.dat")
(load-facts "H_GNP_to_MRS_GNP.dat")
(load-facts "implicit_mrs_concept-pron.dat")
(open "GNP_values.dat" open-file "w")
(open "GNP_values_debug.dat" debug_fp "w")
(watch facts)
(watch rules)
(agenda)
