(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/gen-mrs_feature_info.clp"))
(load ?*path*)
(load-facts "hin_concept-MRS_surface_predicate.dat")
(load-facts "USR-CLIPS-facts.dat")
(load-facts "mrs-rel-features.dat")
(load-facts "hin_concept-MRS_abstract_predicate.dat")
(load-facts "default_MRS_prepositional_concept.dat")
(load-facts "implicit_mrs_concept-pron.dat")
(load-facts "implicit_mrs_concept_compound.dat")
(watch rules)
(watch facts)
(agenda)
