(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/LS-UC_clip_facts.clp"))
(load ?*path*)
(load-facts "USR-CLIPS-facts.dat")
(load-facts "compiled_dict.dat")
(load-facts "tam_mapped.dat")
(open "LS-UC_clips_facts.dat" ls-uc "w")
(open "LS-UC_clips_facts_debug.dat" ls-uc-dbug "w")
(watch facts)
(watch rules)
(agenda)
