(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/default_MRS_prepositional_concept.clp"))
(load ?*path*)
(load-facts "USR-CLIPS-facts.dat")
(load-facts "hin_concept-MRS_abstract_predicate.dat")
(load-facts "hin_concept-MRS_surface_predicate.dat")
(load-facts "karaka_relation_preposition_default_mapping.dat")
(open "default_MRS_prepositional_concept.dat" mrs-def-fp "w")
(open "default_MRS_prepositional_concept_debug.dat" mrs-def-dbug "w")
(watch facts)
(watch rules)
(agenda)
